server:
  port: 18092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 172.16.116.100
  rabbitmq:
    host: 172.16.116.100
    port: 5672
    virtual-host: /fengge
    username: fengge
    password: fengge
    publisher-confirm-type: correlated
    publisher-returns: true
feign:
  sentinel:
    enabled: true
